const MemberList = () => {
   return [
      { first: "Ryan", last: "Crawford", call: "ki5ytk" },
      { first: "Gerald", last: "Patterson", call: "ki5kqt" },
      { first: "Ray", last: "Coffman", call: "nz8o" },
      { first: "Doug", last: "Frisbie", call: "ki5ian" },
      { first: "Mike", last: "Duffell", call: "wb5pmf" },
      { first: "Gary", last: "Metcalf", call: "w0gmm" },
      { first: "Keith", last: "Morrissett", call: "kg5mrn" },
      { first: "Deryl", last: "Graham", call: "ki5mpg" },
      { first: "Tom", last: "Gesell", call: "ki5mph" },
      { first: "Dan", last: "Stone", call: "ki5iao" },
      { first: "Bill", last: "Aycock", call: "k5wca" },
      { first: "Johnny", last: "Rentfro", call: "n5xqk" },
      { first: "Mike", last: "Elliott", call: "n5xr" },
      { first: "Matt", last: "Harker", call: "kc5dbh" },
      { first: "Larry", last: "Rice", call: "n0hdv" },
      { first: "Kent", last: "Kirkham", call: "kc5nwd" },
      { first: "Steve", last: "Pierce", call: "w5biv" },
      { first: "Earl", last: "Matthews", call: "kg5kbx" },
      { first: "Bill", last: "Gerk", call: "w5whg" },
      { first: "Steve", last: "Snyder", call: "ki5bms" },
      { first: "Mike", last: "Belford", call: "n5fry" },
      { first: "Dave", last: "Neel", call: "ke5ccr" },
      { first: "Steve", last: "Tandy", call: "n0slt" },
      { first: "Hubert", last: "Moore", call: "kc5ulf" },
      { first: "Monte", last: "Broadaway", call: "w0mrb" },
      { first: "Monte", last: "Meier", call: "kg5gog" },
      { first: "Ron", last: "Koelling", call: "k5rgk" },
      { first: "Emmett", last: "Casey", call: "ki5spl" },
      { first: "John", last: "Rockwell", call: "kj5roc" },
      { first: "Gene", last: "Hubbard", call: "n5fmj" },
      { first: "Eve", last: "Coffman", call: "k5eac" },
      { first: "Don", last: "Baker", call: "kc5sgy" },
      { first: "Joel", last: "Bennett", call: "kq2o" },
      { first: "Kelly", last: "Teel", call: "k3klt" },
      { first: "Glen", last: "Bishop", call: "wn5j" },
      { first: "Les", last: "Berry", call: "kg5rq" },
      { first: "Garry", last: "Brock", call: "k5olo" },
      { first: "Sharron", last: "Edmondson", call: "kc5sky" },
      { first: "Stan", last: "Thompson", call: "ke5wpx" },
      { first: "David", last: "Hovland", call: "n0ubl" },
      { first: "Jonie", last: "Duffell", call: "ki5ecs" },
      { first: "Robert", last: "Amey", call: "ke5dfo" },
      { first: "Scott", last: "Guffey", call: "ki5ueu" },
      { first: "Tori", last: "Harris", call: "ki5qkj" },
      { first: "Dennis", last: "Covey", call: "ki5uex" },
      { first: "Annie", last: "Shepherd", call: "ki5ues" },
      { first: "Chris", last: "Hunt", call: "n0yh" },
      { first: "Kathy", last: "Hunt", call: "kf0kat" },
      { first: "Terry", last: "Durborow", call: "n5otv" },
      { first: "Michael", last: "Landa", call: "nl7ax" },
      { first: "Bill", last: "Aulick", call: "k0wil" },
   ];
};

export default MemberList;
